version: '3.3'

services:
   wordpress:
     image: wordpress:latest
     ports:
       - "8001:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: 172.17.0.1:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: devops123
